name: Employeefrontend DevSecops Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sonarcloud-scan:
    runs-on: ubuntu-lastest
    steps:
      - name: Step1 Download the Source Code
        uses: actions/checkout@v3.5.3

      - name: Step2 Install Node.js
        uses: actions/setup-node@v3.7.0
        with:
          node-version: "18.16.1"

      - name: Step3 Install Dependencies
        run: npm install

      - name: Step4 SonarCloud    Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=lama
            -Dsonar.projectKey=lama_employeefrontend-fursan-track3
            -Dsonar.sources=.
            -Dsonar.host.url=https://sonarcloud.io

  npm-audit-scan-job:
    name: NPM Audit Scan for Vulnerabilities
    run-on: ubuntu-latest
    steps:
      - name: Step1 download the source code
        uses: actions/checkout@v3.5.3

      - name: Step2 install node.js
        uses: actions/setup-node@v3.7.0
        with:
          node-version: '18.16.1'
      
      - name: Step3 install dependancies
        uses: npm install
      
      - name: Step4 npm audit scan
        uses: npm audit --json > npm-audit-results.json

      - name: Step5 upload npm audit scan report to github
        uses: actions/upload-artifact@3
        with:
          name: npm-audit-results
          path: npm-audit-results.json